// smm/src/components/Navbar.vue
<template>
  <nav class="bg-emerald-700 p-4 flex justify-between items-center shadow-lg fixed top-0 w-full">
    <div class="flex items-center">
      <img src="../assets/Squealer.png" alt="Logo" class="mr-2 h-10 w-auto">
      <router-link to="/" class="text-white text-2xl  font-bold">Squealer For SMMs</router-link>
    </div>
    <div v-if="isUserLoggedIn">
      <button to="/login" class="text-white mr-4 px-4 py-2 border border-white rounded-full hover:bg-white hover:text-emerald-700 focus:outline-none focus:bg-white focus:text-text-emerald-700 font-bold" @click="logout">Logout</button>
    </div>
    <div v-else>
      <router-link to="/login" class="text-white mr-4 px-4 py-2 border border-white rounded-full hover:bg-white hover:text-emerald-700 focus:outline-none focus:bg-white focus:text-text-emerald-700 font-bold" >Login</router-link>
      <router-link to="/register" class="text-white px-4 py-2 border border-white rounded-full hover:bg-white hover:text-emerald-700 focus:outline-none focus:bg-white focus:text-emerald-700 font-bold">Register</router-link>
    </div>
  </nav>        
</template>
<script>
export default {      
  name: 'Navbar',
  computed: {
    isUserLoggedIn() {
      return localStorage.getItem('isUserLoggedIn') === 'true';
    },
  },
  methods: {
    logout(){
      console.log('logout')
      localStorage.clear()
      this.$router.push({ name: 'home' });
      window.location.reload();
    }
  }

};
</script>

// app/src/components/Navbar.tsx
import ContainerBootstrap from 'react-bootstrap/Container';
import NavBootstrap from 'react-bootstrap/Nav';
import NavbarBootstrap from 'react-bootstrap/Navbar';
import Logo from '../assets/squealer-logo.png'
import { NavLink, useNavigate } from 'react-router-dom';


export default function Navbar() {
  const isLoggedIn = !!localStorage.getItem('token')
  const navigate = useNavigate()


  const handleLogout = (e:React.MouseEvent<HTMLElement>) => {
    localStorage.removeItem('token')
    navigate('/')
  }
  console.log(isLoggedIn)
  return (
    <NavbarBootstrap expand="lg" className="bg-flamingo shadow-sm nav-bootstrap">
      <ContainerBootstrap>
        <NavbarBootstrap.Brand to="/" as={NavLink}>
          <img src={Logo} alt="" width="50" height="30" className="d-inline-block align-top mx-2"/>
          Squealer</NavbarBootstrap.Brand>
        <NavbarBootstrap.Toggle aria-controls="basic-navbar-nav" />
        <NavbarBootstrap.Collapse id="basic-navbar-nav">
            {!isLoggedIn ?(
                <NavBootstrap className="ms-auto">
                  <NavBootstrap.Link to="/login" as={NavLink}>Log in</NavBootstrap.Link>
                  <NavBootstrap.Link to="/register" as={NavLink}>Register</NavBootstrap.Link>
                </NavBootstrap>
              ):(
                <NavBootstrap className="ms-auto">
                  <NavBootstrap.Link className="ms-auto" onClick={handleLogout}>Logout</NavBootstrap.Link>
                </NavBootstrap>
              )
            }

        </NavbarBootstrap.Collapse>
      </ContainerBootstrap>
    </NavbarBootstrap>
  );
}
