// app/src/components/Geolocation/map.tsx
import React from "react";
import { LatLngTuple } from 'leaflet';
import { MapContainer, TileLayer, Marker, Polyline, Circle } from 'react-leaflet'
import { cookies } from "next/headers";

interface MapProps {
    coordinates: string;
    isArea: boolean;
}

function coordinatesArrayToLatLngTuples(coordinates: string): LatLngTuple[] {
    const coordinatesArray: string[] = splitStringByPlus(coordinates)
  
    return coordinatesArray.map(coordinates => {
        const parts = coordinates.split(',');
        return [parseFloat(parts[0]), parseFloat(parts[1])] as LatLngTuple;
    });
  }
  
function splitStringByPlus(input: string): string[] {
    return input.split('+');
}


function Map({ coordinates, isArea }: MapProps) {
    const crd: LatLngTuple[] = coordinatesArrayToLatLngTuples(coordinates);
    const center: LatLngTuple = crd[crd.length - 1];

    return (
        <>
        <MapContainer 
            center={center} 
            zoom={13} 
            scrollWheelZoom={false}
            style={{height: '250px'}}
        >
            <TileLayer
                attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
            />
            {/* {crd.map((position, index) => (
                <Marker key={index} position={position}></Marker>
            ))} */}
            <Marker position={center}></Marker>

            <Polyline pathOptions={{color: 'blue'}} positions={crd} />
            {
                isArea ? (
                    <Circle center={crd[0]} pathOptions={{color: 'red'}} radius={400} />
                ) : (
                    <></>
                )
            }

        </MapContainer>
        </>
    );
}

export default Map;

// smm/src/components/Map.vue
<template>
  <div>
    <l-map :zoom="13" :center="center" style="height: 300px">
      <l-tile-layer
        url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      ></l-tile-layer>

      <l-marker :lat-lng="center"></l-marker>

      <l-polyline
        v-if="crd.length > 1"
        :lat-lngs="crd"
        :options="{ color: 'blue' }"
      ></l-polyline>

      <l-circle
        v-if="isArea"
        :lat-lng="crd[0]"
        :radius="400"
        :options="{ color: 'red' }"
      ></l-circle>
    </l-map>
  </div>
</template>

<script>
import "leaflet/dist/leaflet.css";
import { latLng } from "leaflet";
import { LMap, LTileLayer, LMarker, LPolyline, LCircle } from "@vue-leaflet/vue-leaflet";

export default {
  components: { LMap, LTileLayer, LMarker, LPolyline, LCircle },
  props: {
    coordinates: String,
    isArea: Boolean,
  },
  computed: {
    crd() {
      return this.coordinatesArrayToLatLngTuples(this.coordinates);
    },
    center() {
      return this.crd.length ? this.crd[this.crd.length - 1] : latLng(0, 0);
    },
  },
  methods: {
    coordinatesArrayToLatLngTuples(coordinates) {
      const coordinatesArray = this.splitStringByPlus(coordinates);
      return coordinatesArray.map((coordinates) => {
        const parts = coordinates.split(",");
        return latLng(parseFloat(parts[0]), parseFloat(parts[1]));
      });
    },
    splitStringByPlus(input) {
      return input.split("+");
    },
  },
};
</script>
